version: 2

sources:
  - name: sources
    database: workspace
    schema: northwind
    tables:
      - name: categories
      - name: products
      - name: suppliers
      - name: employees
      - name: order_details
      - name: customers
      - name: orders
      - name: shippers